---
- hosts: elastic
  become: yes
  gather_facts: no
  vars:
    image: ads
  tasks:
    - name: upload configs
      copy:
        src: './containers'
        dest: '~/elastic/'
    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: ~/elastic/containers
        files:
        - docker-compose.yml
