---
- hosts: app
  gather_facts: no
  become: yes
  vars_files:
    - vars/docker-vars.yml

  tasks:
    - name: Install aptitude using apt
      become: yes
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages for Docker
      become: yes
      apt: name={{ docker_required_packages }} state=latest update_cache=yes

    - name: Add Docker GPG key
      become: yes
      apt_key:
        url: "{{ docker_gpg_url }}"
        state: present

    - name: Add Docker repository
      become: yes
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: Install Docker Compose
      become: yes
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: u+x,g+x,o+x