---
- hosts: db
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name:
          - acl
          - gnupg
          - postgresql
          - libpq-dev
          - python3-psycopg2
- hosts: db
  become: yes
  become_user: postgres
  gather_facts: no
  vars:
    ads_database: ads_microservice_production
    auth_database: auth_microservice_production
    user: ads
    password: '{{ postgresql_password }}'
  vars_files:
    - secrets.yml
  tasks:
    - name: ensure ads_database is created
      postgresql_db:
        name: '{{ ads_database }}'
    - name: ensure auth_database is created
      postgresql_db:
        name: '{{ auth_database }}'
    - name: ensure user has access to ads_database
      postgresql_user:
        db: '{{ ads_database }}'
        name: '{{ user }}'
        password: '{{ password }}'
        priv: ALL
    - name: ensure user has access to auth_database
      postgresql_user:
        db: '{{ auth_database }}'
        name: '{{ user }}'
        password: '{{ password }}'
        priv: ALL
    - name: ensure user has no extra privileges
      postgresql_user:
        name: '{{ user }}'
        role_attr_flags: NOSUPERUSER,NOCREATEDB
    - name: ensure no other user can access the ads_database
      postgresql_privs:
        db: '{{ ads_database }}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent
    - name: ensure no other user can access the auth_database
      postgresql_privs:
        db: '{{ auth_database }}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent
